# Messages
AUTHORIZATION_HEADER_DESC = 'Bearer token to access protected resources'
BEARER_TOKEN_REQUIRED = 'Bearer token required'
INVALID_CREDENTIALS = 'Invalid username or password'
INVALID_REFRESH_TOKEN = 'Invalid refresh token'
NOT_ENOUGH_PERMISSIONS = 'Not enough permissions'
NOT_FOUND = 'Not Found'
SUCCESSFUL_LOGIN = 'Successful login'
SUCCESSFULLY_ADDED = 'Successfully added'
SUCCESSFULLY_DELETED = 'Successfully deleted'
SUCCESSFULLY_UPDATED = 'Successfully updated'
